name: Hello world workflow

on:
   push:
     branches:
       - main
   pull_request: 
     branches:
       - main
   workflow_dispatch:

jobs:
  hello:
    runs-on: macos_Ventura
    steps:
      - uses: actions/checkout@v2
      - name: hello world
         run: echo "hello world"
         shell: bash

  goodbye:
     runs-on: macos_ventura
     steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash
  